
const Types = {
        MAKE_API_CALL: "MAKE_API_CALL",
        API_RESPONSE_SUCESS: "API_RESPONSE_SUCESS",
        API_RESPONSE_FAIL: "API_RESPONSE_FAIL",
        CHANGE_HIGHLIGHTED_CONTENT: "CHANGE_HIGHLIGHTED_CONTENT",
        SET_INFO_VISIBLITY: "SET_INFO_VISIBLITY",
        SET_VIDEO_URL: "SET_VIDEO_URL"
}

export default Types